from enum import Enum

class MessageTypesConnectionDB(Enum):
    SERVER_SELECTION_TIMEOUT_ERROR=1
    OPERATION_FAILURE=2
    INVALID_OPERATION=3
    AUTO_RECONNECT=4
    CONNECTION_FAILURE=5
    PY_MONGO_ERROR=6
    EXCEPTION=7
    SAVE_OK=8
    CREATE_CONNECTION_OK=9
    BUILD_DATABASE_CLASSES_OK=10
    LOAD_DATABASE_OK=11
    SERVER_INFO_OK=12
    CLOSE_OK=13
    ALREADY_SAVED=14
    NOT_CLIENT_CONNECTED=15
    ALREADY_CLIENT_CONNECTED=16
    INADEQUATE_DATABASE=17
    DATABASES_ARE_ALREADY_BUILT=18
    DATABASE_CLASSES_NOT_BUILT=19
    NOT_URI=20